### ISSUE TITLE
Outlines around link elements

### ISSUE THREAD

**Issue by alisonjo2786** [CommerceGov/DataCorps_WebSite#8]
If you don't mind, please add the following to your CSS (or find and remove whatever's overriding what we have on c.gov) -- those dotted-borders when you click on "a" elements are driving me nuts!

```css
a:focus, a:hover, a:active { outline: 0; }
```
